version: "3.8"
services:
  lavalink:
    build: .
    container_name: lavalink
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      - _JAVA_OPTIONS=-Xmx1G
      # You can also set environment variables for config overrides
      - SERVER_PORT=443
      - LAVALINK_SERVER_PASSWORD=yoursecretpassword
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
